source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GearKit_Example', :exclusive => true do
  pod 'GearKit', :path => '../'
end

target 'GearKit_Tests', :exclusive => true do
  pod 'GearKit', :path => '../'

  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 4'
  pod 'SwiftyJSON', '> 2'
end
